name: Maven tests with JaCoCo Coverage

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17 for the environment
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run Maven tests and generate JaCoCo reports
      - name: Run Maven tests and generate JaCoCo report
        run: mvn clean verify

      # Step 4: Get JaCoCo Coverage
      - name: Get JaCoCo Coverage
        id: coverage
        run: |
          # Extract coverage percentage from the JaCoCo CSV report
          coverage=$(grep -Eo 'INSTRUCTION.*' target/site/jacoco/jacoco.csv | awk -F, '{total+=$2;missed+=$3} END {print 100*(total-missed)/total}')
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
          echo "Coverage: $coverage%"

      # Step 5: Fail if coverage has not improved
      - name: Fail if coverage has not improved
        run: |
          coverage=$COVERAGE
          threshold=81.58
          if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
            echo "Coverage has not improved."
            exit 1
          else
            echo "New coverage: $coverage%"
          fi

      # Step 6: Upload JaCoCo coverage report as an artifact
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco
